### ISSUE TITLE
斷詞輸出格式回傳 list

### ISSUE THREAD

**Issue by ckmarkoh** [ckmarkoh/deepSeg#2]

**Comment by fukuball** [comment]
- 斷詞輸出格式回傳 list，比較容易使用
- 未來有命令列格式時，再讓使用者可以自定回傳斷詞字串

**Comment by fukuball** [comment]
我來改這個，先把簡單的幹掉～

**Comment by drumrick** [comment]
因為code format的關係，issue2的line_in每一行前面都有空白
導致output list的第一個元素都是空字串
我覺得
1. DeepSeg拿到輸入後要先strip一下 （可能需要一個custom strip去掉全形空白）
2. line_in 的 padding whitespace要拿掉
3. 統一一下code format，這樣未來code review才不會太痛苦
你們覺得如何

**Comment by fukuball** [comment]
1. strip 空白沒問題，應該要做
2. 如果 strip 空白這個問題是否就解決了？
3. coding style 不知目前有沒有什麼標準？（tab 空格幾格、method 命名 format）

**Comment by fukuball** [comment]
@drumrick  我剛剛實際跑，好像已經會 strip 掉空白了耶，所以現在問題剩下我們要遵循哪個 coding style 標準，你有推薦的嗎？

**Comment by drumrick** [comment]
關於strip我錯了
每一行開頭的兩個空白
是因為output_line.append("\n")
然後在**main**裡面 join 之後跑出來的

**Comment by drumrick** [comment]
coding style我是腦補pep8拉

我會提這個是因為mark的逗號後面沒有空白
你的commit有加上去
我也是習慣有空白拉
我以為你的是editor自動幫你加的
如果是的話可能mark那邊也要用一樣的
未來commit裡才不會很多這種東西

**Comment by fukuball** [comment]
那我們就來使用 PEP8，https://pypi.python.org/pypi/pep8，我晚一點來寫一下我們協作的流程，這樣才比較好合作～

**Comment by drumrick** [comment]
closed by https://github.com/ckmarkoh/deepSeg/pull/5
